S    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_hr-hr_76db87bbec7909b1, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_hu-hu_9949e046bc8c8e47 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_hu-hu_780fad81ebb66b19, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_it-it_3c015645af5ea4a9 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_it-it_1ac72380de88817b, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_ja-jp_de26d552a279b684 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_ja-jp_bceca28dd1a39356, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_ko-kr_8190b20794ea7d9a (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_ko-kr_60567f42c4145a6c, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_lt-lt_255bde0887124937 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_lt-lt_0421ab43b63c2609, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_lv-lv_26294c8c86908a27 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_lv-lv_04ef19c7b5ba66f9, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_nb-no_6a23333c6d0fa956 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_nb-no_48e900779c398628, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_nl-nl_68627e7a6e3bb32b (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_nl-nl_47284bb59d658ffd, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_pl-pl_ae9ed8fc535e20df (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_pl-pl_8d64a6378287fdb1, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_pt-br_b0f2c3a051e7b4c3 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_pt-br_8fb890db81119195, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_pt-pt_b1d4930c5157249f (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_pt-pt_909a604780810171, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_ro-ro_f60f594437bdeffb (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_ro-ro_d4d5267f66e7cccd, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_ru-ru_f877a4d03638b2cb (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_ru-ru_d73d720b65628f9d, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_sk-sk_9792a97d2b52a4f5 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_sk-sk_765876b85a7c81c7, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_sl-si_96a4cb352becb7d8 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_sl-si_756a98705b1694aa, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_sr-..-cs_362e47c7a5451b20 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_sr-..-cs_14f41502d46ef7f2, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_sv-se_94728f452d61bd26 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_sv-se_73385c805c8b99f8, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_th-th_397cb0f81ea67a67 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_th-th_18427e334dd05739, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_tr-tr_3d7fd98c1c1dbf17 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_tr-tr_1c45a6c74b479be9, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_uk-ua_d95fbc33134ee563 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_uk-ua_b825896e4278c235, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_zh-cn_0edcf789cc559136 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_zh-cn_eda2c4c4fb7f6e08, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_zh-hk_0d87f017cd3103c6 (6.1.7601.22708), elevation:2, lower version revision holder: 0.0.0.0
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_zh-hk_ec4dbd52fc5ae098, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_0.0.0.0_zh-tw_12d934dfc9c66da6 (6.1.7601.22708), elevation:2, lower version revision holder: 6.1.7601.18906
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_zh-tw_f19f021af8f04a78, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: x86_microsoft-windows-authentication-authui_31bf3856ad364e35_0.0.0.0_none_2fcd72c43d921e2d (6.1.7601.22708), elevation:2, lower version revision holder: 6.1.7601.18906
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: x86_microsoft-windows-authentication-authui_31bf3856ad364e35_6.1.7601.22708_none_0e933fff6cbbfaff, elevate: 2, applicable(true/false): 0
2016-02-02 11:09:05, Info                  CBS    Appl: SelfUpdate detect, component: amd64_microsoft-windows-a..on-authui.resources_31bf3856ad364e35_6.1.7601.22708_ar-sa_559b525b07b87b4c, elevation: 2, applicable: 0
2016-02-02 11:09:05, Info                  CBS    Appl: Evaluating applicability block(non detectUpdate part), disposition is: Staged, applicability: NotApplicable, result applicability state: Staged
2016-02-02 11:09:05, Info                  CBS    Appl: Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: Trigger_1, Applicable: NotApplicable, Disposition: Staged
2016-02-02 11:09:05, Info                  CBS    Appl: DetectUpdate, Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Local Parent: Trigger_1, Intended State: Staged
2016-02-02 11:09:05, Info                  CBS    Appl: Evaluating applicability block(detectUpdate part), disposition is: Staged, applicability: NotApplicable, result applicability state: Staged
2016-02-02 11:09:05, Info                  CBS    Appl: Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: 2918614-232_neutral_LDR, Applicable: NeedsParent, Disposition: Staged
2016-02-02 11:09:05, Info                  CBS    Plan: Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: 2918614-232_neutral_LDR, current: Staged, pending: Default, start: Staged, applicable: Staged, targeted: Staged, limit: Installed, selected: Default
2016-02-02 11:09:05, Info                  CBS    Appl: Selfupdate, Component: amd64_microsoft-windows-authentication-authui_31bf3856ad364e35_0.0.0.0_none_8bec0e47f5ef8f63 (6.1.7601.18493), elevation:2, lower version revision holder: 6.1.7601.18276
2016-02-02 11:09:05, Info                  CBS    Applicability(ComponentAnalyzerEvaluateSelfUpdate): Component: amd64_microsoft-windows-authentication-authui_31bf3856ad364e35_6.1.7601.18493_none_69c1ea2e0c494ee3, elevate: 2, applicable(true/false): 1
2016-02-02 11:09:05, Info                  CBS    Appl: SelfUpdate detect, component: amd64_microsoft-windows-authentication-authui_31bf3856ad364e35_6.1.7601.18493_none_69c1ea2e0c494ee3, elevation: 2, applicable: 1
2016-02-02 11:09:05, Info                  CBS    Appl: Evaluating applicability block(non detectUpdate part), disposition is: Staged, applicability: Applicable, result applicability state: Installed
2016-02-02 11:09:05, Info                  CBS    Appl: Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: 2918614-233_neutral_GDR, Applicable: Applicable, Disposition: Installed
2016-02-02 11:09:05, Info                  CBS    Plan: Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: 2918614-233_neutral_GDR, current: Installed, pending: Default, start: Installed, applicable: Installed, targeted: Installed, limit: Installed, selected: Default
2016-02-02 11:09:05, Info                  CBS    Exec: Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4 is already in the correct state, current: Installed, targeted: Installed
2016-02-02 11:09:05, Info                  CBS    Exec: Skipping Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: 2918614-231_neutral_LDR because it is already in the correct state.
2016-02-02 11:09:05, Info                  CBS    Exec: Skipping Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: 2918614-232_neutral_LDR because it is already in the correct state.
2016-02-02 11:09:05, Info                  CBS    Exec: Skipping Package: Package_79_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Update: 2918614-233_neutral_GDR because it is already in the correct state.
2016-02-02 11:09:05, Info                  CBS    Appl: detect Parent, Package: Package_40_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, Parent: Microsoft-Windows-Foundation-Package~31bf3856ad364e35~amd64~~6.1.7601.17514, Disposition = Detect, VersionComp: EQ, ServiceComp: EQ, BuildComp: EQ, DistributionComp: GE, RevisionComp: GE, Exist: present
2016-02-02 11:09:05, Info                  CBS    Appl: detectParent: package: Package_40_for_KB2918614~31bf3856ad364e35~amd64~~6.1.1.4, parent found: Microsoft-Windows-Foundation-Package~31bt;"
    # i 為行序
    for i in range(len(final_result)):
        # j 為組員序
        for j in range(len(final_result[i])):
            num_of_stud += 1
            tmp_string += final_result[i][j] + ","
        out_string += "第" + str(i+1) + "組:"+ tmp_string + "&lt;br /&gt;"
        tmp_string = ""
    #return "總共有" + str(i+) + "組"
    # group_num 為總組數
    group_num = i + 1
    # 截至這裡, 已經完成選組長, 以及定組序的工作 ,接下來要排座位, 並且印出座位表
    # 先算每班的總人數
    #return "總共有"+ str(num_of_stud) + "人"
    seat_by_column = []
    for row in range(max_num_in_one_group):
    # 每組最多 7 人
    #for row in range(7):
        # 這裡的 11 為總組數
        #for column in range(11):
        for column in range(group_num):
            # 因為各分組數列的長度並不相同, 但是最長的有 7 位組員, 因此若無法取得的資料 (因為索引超值), 就補上空字串
            try:
                seat_by_column.append(final_result[column][row])
            except:
                seat_by_column.append("")
    # seat_by_column 為去除空白字串前的座位數列
    # 然後利用 filter(None, seat_by_column) 去除空白字串, 就可以得到以 column 為主的座位排序
    seat_by_column = list(filter(None, seat_by_column))
    # 然後每 N 個取為 1 排, 即可得到以排為主的座位序列, 而 N 則視全班人數除以 9, 也就是 total_column 進位決定, 因為共有 9 排
    N = math.ceil(num_of_stud/total_column)
    # for debug
    #return str(num_of_stud) + ":" + str(total_column) + ":" + str(N)
    column_list = [seat_by_column[n:n+N] for n in range(0, len(seat_by_column), N)]
    # 列出每 N 個組員一排的數列 column_list
    # 接下來要納入以排為主的座位
    # 根據 column_list, 建立一個 dictionary, 其中學號為 index, 座位號為對應值
    seat_dict = {}
    for column in range(len(column_list)):
        for i in range(N):
            try:
                seat_dict.update({column_list[column][i]: (column, i)})
            except:
                seat_dict.update({"": ""})
                
    # 開始準備用順序列出學員座號
    # 根據學號, 排序 dictionary 的方法
    import operator
    seat_dict_sort = sorted(seat_dict.items(), key = operator.itemgetter(0), reverse = False)
    # 依照學號順序, 列出座位表
    out_string += "&lt;br /&gt;按照學號次序列出座位表:&lt;br /&gt;&lt;br /&gt;"
    for i in range(1, len(seat_dict_sort)):
        out_string +=  str(i) + ":"+ str(seat_dict_sort[i]) + "&lt;br /&gt;"
    # 結束準備用順序列出學員座號
    # dont know why .reverse() did not work, 只有 [::-1] 可以 reverse list elements
    #g.es(column_list[::-1])

    # 因為經由 zip 逐一重新 transpose 的列資料, 必須配合最大 (也就是總共有 7 列, 也就是 N 的值) 列數補上空白字串 (也就是空位)
    # 所以不能使用 zip, 而必須導入 zip_longest 模組方法
    from itertools import zip_longest
    final_seat = list(zip_longest(*column_list[::-1], fillvalue=""))
    # 列出最後的座位表
    #g.es(final_seat)
    # 最後轉成 html table 標註格式
    out_string += "&lt;br /&gt; &lt;br /&gt;"
    out_string += "&lt;table border='1' width='100%'&gt;"
    out_string += "&lt;tr&gt;&lt;td colspan='9' style='text-align:center'&gt;講台&lt;/td&gt;&lt;/tr&gt;"
    for row in range(len(final_seat)):
        out_string += "&lt;tr&gt;"
        # 因為每一 row 有 9, 也就是 total_column 個位子
        for i in range(total_column):
            try:
                if i%2 != 0:
                    out_string += "&lt;td style='text-align:center'  bgcolor='#FFD78C' height='30'&gt;" + str(final_seat[row][i]) + "&lt;/td&gt;"
                else:
                    out_string += "&lt;td style='text-align:center' height='30'&gt;" + str(final_seat[row][i]) + "&lt;/td&gt;"
            except:
                out_string += "&lt;td&gt;&amp;nbsp;&lt;/td&gt;"
        out_string += "&lt;/tr&gt;"
    out_string += "&lt;/table&gt;&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;"
    return out_string
    # 等運算或資料處理結束後, 再將相關值送到對應的 template 進行資料的展示
    #return render_template('optionaction.html', option_list1=option_list1, option_list2=option_list2)
    

</t>
<t tx="amd.20160501221015.1"></t>
<t tx="amd.20160501225844.1"># setup static directory
@app.route('/static/&lt;path:path&gt;')
def send_file(path):
  return app.send_static_file(static_dir+path)

</t>
<t tx="amd.20160501230850.1"># setup static directory
@app.route('/static/blog/')
def send_blog():
  return app.send_static_file('blog/index.html')

</t>
<t tx="leo.20160509082623.1"></t>
<t tx="leo.20160509082623.2">(uncached) amd.20160501221001.2
Diff...
  # coding: utf-8
  from flask import Flask, send_from_directory, request, redirect, render_template, session, make_response
  import random
  import math
  import os
  # init.py 為自行建立的起始物件
  import init
  
- import users.a.g10.ag10_40323129_task1
- import users.a.g10.ag10_40323141_task1
- import users.a.g10.ag10_40323139
?                  -    -       ^^
+ import users.a.g1.ag1_40323105
?                             ^^
- import users.a.g9.ag9_40323132task
- import users.a.g5.ag5_40323113task1
- import users.a.g4.ag4_40323138
- import users.a.g4.ag4_40323138_task2bacd
- import users.a.g4.ag4_40323138_task3abcd
- import users.a.g8.ag8_40323131_task1
- import users.b.g9.bg9_40323250
- import users.b.g11.bg11_40323245
- import users.b.g1.bg1_40123156
- #bg2
- import users.b.g2.bg2_40123235
- import users.b.g2.bg2_40123202
- #bg4
- import users.b.g4.bg4_40323203
  # 確定程式檔案所在目錄, 在 Windows 有最後的反斜線
  _curdir = os.path.join(os.getcwd(), os.path.dirname(__file__))
  # 設定在雲端與近端的資料儲存目錄
  if 'OPENSHIFT_REPO_DIR' in os.environ.keys():
      # 表示程式在雲端執行
      data_dir = os.environ['OPENSHIFT_DATA_DIR']
      static_dir = os.environ['OPENSHIFT_REPO_DIR']+"/static"
      download_dir = os.environ['OPENSHIFT_DATA_DIR']+"/downloads"
  else:
      # 表示程式在近端執行
      data_dir = _curdir + "/local_data/"
      static_dir = _curdir + "/static"
      download_dir = _curdir + "/local_data/downloads/"
  
  # 利用 init.py 啟動, 建立所需的相關檔案
  initobj = init.Init()
  
  # 必須先將 download_dir 設為 static_folder, 然後才可以用於 download 方法中的 app.static_folder 的呼叫
  app = Flask(__name__)
  #app.config['download_dir'] = download_dir
  
  # 使用 session 必須要設定 secret_key
  # In order to use sessions you have to set a secret key
  # set the secret key.  keep this really secret:
  app.secret_key = 'A0Zr9@8j/3yX R~XHH!jmN]LWX/,?R@T'
  
  
  
  
  
  
  
  
</t>
<t tx="leo.20160509082623.3"># coding: utf-8
from flask import Flask, send_from_directory, request, redirect, render_template, session, make_response
import random
import math
import os
# init.py 為自行建立的起始物件
import init

import users.a.g1.ag1_40323105
# 確定程式檔案所在目錄, 在 Windows 有最後的反斜線
_curdir = os.path.join(os.getcwd(), os.path.dirname(__file__))
# 設定在雲端與近端的資料儲存目錄
if 'OPENSHIFT_REPO_DIR' in os.environ.keys():
    # 表示程式在雲端執行
    data_dir = os.environ['OPENSHIFT_DATA_DIR']
    static_dir = os.environ['OPENSHIFT_REPO_DIR']+"/static"
    download_dir = os.environ['OPENSHIFT_DATA_DIR']+"/downloads"
else:
    # 表示程式在近端執行
    data_dir = _curdir + "/local_data/"
    static_dir = _curdir + "/static"
    download_dir = _curdir + "/local_data/downloads/"

# 利用 init.py 啟動, 建立所需的相關檔案
initobj = init.Init()

# 必須先將 download_dir 設為 static_folder, 然後才可以用於 download 方法中的 app.static_folder 的呼叫
app = Flask(__name__)
#app.config['download_dir'] = download_dir

# 使用 session 必須要設定 secret_key
# In order to use sessions you have to set a secret key
# set the secret key.  keep this really secret:
app.secret_key = 'A0Zr9@8j/3yX R~XHH!jmN]LWX/,?R@T'








</t>
<t tx="leo.20160509082623.4"># coding: utf-8
from flask import Flask, send_from_directory, request, redirect, render_template, session, make_response
import random
import math
import os
# init.py 為自行建立的起始物件
import init

import users.a.g10.ag10_40323129_task1
import users.a.g10.ag10_40323141_task1
import users.a.g10.ag10_40323139
import users.a.g9.ag9_40323132task
import users.a.g5.ag5_40323113task1
import users.a.g4.ag4_40323138
import users.a.g4.ag4_40323138_task2bacd
import users.a.g4.ag4_40323138_task3abcd
import users.a.g8.ag8_40323131_task1
import users.b.g9.bg9_40323250
import users.b.g11.bg11_40323245
import users.b.g1.bg1_40123156
#bg2
import users.b.g2.bg2_40123235
import users.b.g2.bg2_40123202
#bg4
import users.b.g4.bg4_40323203
# 確定程式檔案所在目錄, 在 Windows 有最後的反斜線
_curdir = os.path.join(os.getcwd(), os.path.dirname(__file__))
# 設定在雲端與近端的資料儲存目錄
if 'OPENSHIFT_REPO_DIR' in os.environ.keys():
    # 表示程式在雲端執行
    data_dir = os.environ['OPENSHIFT_DATA_DIR']
    static_dir = os.environ['OPENSHIFT_REPO_DIR']+"/static"
    download_dir = os.environ['OPENSHIFT_DATA_DIR']+"/downloads"
else:
    # 表示程式在近端執行
    data_dir = _curdir + "/local_data/"
    static_dir = _curdir + "/static"
    download_dir = _curdir + "/local_data/downloads/"

# 利用 init.py 啟動, 建立所需的相關檔案
initobj = init.Init()

# 必須先將 download_dir 設為 static_folder, 然後才可以用於 download 方法中的 app.static_folder 的呼叫
app = Flask(__name__)
#app.config['download_dir'] = download_dir

# 使用 session 必須要設定 secret_key
# In order to use sessions you have to set a secret key
# set the secret key.  keep this really secret:
app.secret_key = 'A0Zr9@8j/3yX R~XHH!jmN]LWX/,?R@T'








</t>
</tnodes>
</leo_file>
